title: Senior Celebration May 24, 2020
description: site description
midd_url: https://www.middlebury.edu
nav:
  - text: List of Graduates
    url: /graduates
  - text: Department Receptions
    url: /receptions
  - text: Honorary Degrees
    url: /honorary-degrees
  - text: Program
    url: /program
  - text: Credits for Senior Montage
    url: /credits

footer:
  - text: About Middlebury
    href: http://www.middlebury.edu/about
  - text: Giving
    href: http://www.middlebury.edu/giving
  - text: Employment
    href: http://www.middlebury.edu/offices/business/hr/jobseeker
  - text: Offices and Services
    href: http://www.middlebury.edu/office/
  - text: Copyright
    href: http://www.middlebury.edu/about/copyright
  - text: Privacy
    href: http://www.middlebury.edu/about/privacy
